[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@account-abstraction=lib/account-abstraction",
    "@openzeppelin-contracts=lib/openzeppelin-contracts",
    "@forge-std=lib/forge-std",
]
is-system = true
via-ir = true
optimizer = true
optimizer_runs = 200
